version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
        command: |
            python3 -m venv numberword
            . numberword/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "numberword"
    
      - run:
          name: Running tests
          command: |
            . numberword/bin/activate
            python3 converterTests.py
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-reports/
          destination: number-worder